### PR TITLE
Read frequency_penalty from configuration.toml and add it to all stages. The stages can still overwrite it.

### PR DESCRIPTION
**Pull request by Majdoddin**
## **User description**
whithout frequency_penalty ChatGPT makes infinte stream (?). For example in 'generate ai tests', for problem 80 - optimal insertion

___

## **Type**
Enhancement

___

## **Description**
- This PR reads frequency_penalty from configuration.toml in the `alpha_codium/settings` directory and adds it to all stages. The toml confiuration files of the stages can still overwrite it. 
- This PR introduces the `frequency_penalty` parameter to various toml configuration files in the `alpha_codium/settings` directory.
- The addition of this parameter is aimed at preventing infinite stream generation by ChatGPT.
___

## **Changes walkthrough**
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Configuration changes</strong></td><td><details><summary>10 files</summary><table>
<tr>
  <td>
    <details>
      <summary><strong>choose_best_solution_direct.toml</strong><dd><code>Addition of `frequency_penalty` parameter</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
alpha_codium/settings/choose_best_solution_direct.toml

- Added `frequency_penalty` parameter.

    </details>
  </td>
  <td><a href="https://github.com/Codium-ai/AlphaCodium/pull/25/files#diff-39aac0718bf94f6f670baa40d29290f1333dcadf95e98d10a3fd20f4f92fc3ce">+1/-0</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>code_contests_prompt_analyze_and_fix.toml</strong><dd><code>Addition of `frequency_penalty` parameter</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
alpha_codium/settings/code_contests_prompt_analyze_and_fix.toml

- Added `frequency_penalty` parameter.

    </details>
  </td>
  <td><a href="https://github.com/Codium-ai/AlphaCodium/pull/25/files#diff-fa9d7c99c0507b85ccfae68369e1834844b4f24e8d70642055a9051b14ff2294">+1/-0</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>code_contests_prompt_analyze_and_fix_direct.toml</strong><dd><code>Addition of `frequency_penalty` parameter</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
alpha_codium/settings/code_contests_prompt_analyze_and_fix_direct.toml

- Added `frequency_penalty` parameter.

    </details>
  </td>
  <td><a href="https://github.com/Codium-ai/AlphaCodium/pull/25/files#diff-9edc107624724fbcafa7b586110dc01357af98d271dc197c35ff0a05627e4b32">+1/-0</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>code_contests_prompt_analyze_failure.toml</strong><dd><code>Addition of `frequency_penalty` parameter</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
alpha_codium/settings/code_contests_prompt_analyze_failure.toml

- Added `frequency_penalty` parameter.

    </details>
  </td>
  <td><a href="https://github.com/Codium-ai/AlphaCodium/pull/25/files#diff-7ea281be2fc1e9a9db4e94c46336096ff7acd62cee921f59ef60da015c2bbfba">+1/-0</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>code_contests_prompts_baseline.toml</strong><dd><code>Addition of `frequency_penalty` parameter</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
alpha_codium/settings/code_contests_prompts_baseline.toml

- Added `frequency_penalty` parameter.

    </details>
  </td>
  <td><a href="https://github.com/Codium-ai/AlphaCodium/pull/25/files#diff-e0d4eefec70164f0b747bcb68d59f743e84fd16eec91e71349d0a3a9fa97d92a">+1/-0</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>code_contests_prompts_fix_solution.toml</strong><dd><code>Addition of `frequency_penalty` parameter</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
alpha_codium/settings/code_contests_prompts_fix_solution.toml

- Added `frequency_penalty` parameter.

    </details>
  </td>
  <td><a href="https://github.com/Codium-ai/AlphaCodium/pull/25/files#diff-223fce453abd289a1ca88b8a223efe96017e54e731bb1a8fa34b978824621aeb">+1/-0</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>code_contests_prompts_generate_ai_tests.toml</strong><dd><code>Addition of `frequency_penalty` parameter</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
alpha_codium/settings/code_contests_prompts_generate_ai_tests.toml

- Added `frequency_penalty` parameter.

    </details>
  </td>
  <td><a href="https://github.com/Codium-ai/AlphaCodium/pull/25/files#diff-54b86dd019deffa4b7b2285d29c9409738a096a57cbc9dfa67ac2571d299f920">+1/-0</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>code_contests_prompts_generate_possible_solutions.toml</strong><dd><code>Addition of `frequency_penalty` parameter</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
alpha_codium/settings/code_contests_prompts_generate_possible_solutions.toml

- Added `frequency_penalty` parameter.

    </details>
  </td>
  <td><a href="https://github.com/Codium-ai/AlphaCodium/pull/25/files#diff-0254850e83e9f0867a89d6616db9780919ae0c6fafbd4a40a16e11ca280155eb">+1/-0</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>code_contests_prompts_solve.toml</strong><dd><code>Addition of `frequency_penalty` parameter</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
alpha_codium/settings/code_contests_prompts_solve.toml

- Added `frequency_penalty` parameter.

    </details>
  </td>
  <td><a href="https://github.com/Codium-ai/AlphaCodium/pull/25/files#diff-0c2d616b49b96a00559c5c2c60d059746e57fca605c1bf3cee783a11b3970525">+1/-0</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>code_contests_prompts_solve_direct.toml</strong><dd><code>Addition of `frequency_penalty` parameter</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
alpha_codium/settings/code_contests_prompts_solve_direct.toml

- Added `frequency_penalty` parameter.

    </details>
  </td>
  <td><a href="https://github.com/Codium-ai/AlphaCodium/pull/25/files#diff-1863d7bb132896bc7722ba9e0e8804c07bb84fd0717fa23f90be566c0f014681">+1/-0</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    
</table></details></td></tr></tr></tbody></table><hr>

<details> <summary><strong>✨ Usage guide:</strong></summary><hr> 

**Overview:**
The `describe` tool scans the PR code changes, and generates a description for the PR - title, type, summary, walkthrough and labels. The tool can be triggered [automatically](https://github.com/Codium-ai/pr-agent/blob/main/Usage.md#github-app-automatic-tools) every time a new PR is opened, or can be invoked manually by commenting on a PR.

When commenting, to edit [configurations](https://github.com/Codium-ai/pr-agent/blob/main/pr_agent/settings/configuration.toml#L46) related to the describe tool (`pr_description` section), use the following template:
```
/describe --pr_description.some_config1=... --pr_description.some_config2=...
```
With a [configuration file](https://github.com/Codium-ai/pr-agent/blob/main/Usage.md#working-with-github-app), use the following template:
```
[pr_description]
some_config1=...
some_config2=...
```

<table><tr><td><details> <summary><strong> Enabling\disabling automation </strong></summary><hr>

- When you first install the app, the [default mode](https://github.com/Codium-ai/pr-agent/blob/main/Usage.md#github-app-automatic-tools) for the describe tool is:
```
pr_commands = ["/describe --pr_description.add_original_user_description=true" 
                         "--pr_description.keep_original_user_title=true", ...]
```
meaning the `describe` tool will run automatically on every PR, will keep the original title, and will add the original user description above the generated description. 

- Markers are an alternative way to control the generated description, to give maximal control to the user. If you set:
```
pr_commands = ["/describe --pr_description.use_description_markers=true", ...]
```
the tool will replace every marker of the form `pr_agent:marker_name` in the PR description with the relevant content, where `marker_name` is one of the following:
  - `type`: the PR type.
  - `summary`: the PR summary.
  - `walkthrough`: the PR walkthrough.

Note that when markers are enabled, if the original PR description does not contain any markers, the tool will not alter the description at all.
        

</details></td></tr>

<tr><td><details> <summary><strong> Custom labels </strong></summary><hr>

The default labels of the `describe` tool are quite generic: [`Bug fix`, `Tests`, `Enhancement`, `Documentation`, `Other`].

If you specify [custom labels](https://github.com/Codium-ai/pr-agent/blob/main/docs/DESCRIBE.md#handle-custom-labels-from-the-repos-labels-page-gem) in the repo's labels page or via configuration file, you can get tailored labels for your use cases.
Examples for custom labels:
- `Main topic:performance` - pr_agent:The main topic of this PR is performance
- `New endpoint` - pr_agent:A new endpoint was added in this PR
- `SQL query` - pr_agent:A new SQL query was added in this PR
- `Dockerfile changes` - pr_agent:The PR contains changes in the Dockerfile
- ...

The list above is eclectic, and aims to give an idea of different possibilities. Define custom labels that are relevant for your repo and use cases.
Note that Labels are not mutually exclusive, so you can add multiple label categories.
Make sure to provide proper title, and a detailed and well-phrased description for each label, so the tool will know when to suggest it.        

</details></td></tr>

<tr><td><details> <summary><strong> Inline File Walkthrough 💎</strong></summary><hr>

For enhanced user experience, the `describe` tool can add file summaries directly to the "Files changed" tab in the PR page.
This will enable you to quickly understand the changes in each file, while reviewing the code changes (diffs).

To enable inline file summary, set `pr_description.inline_file_summary` in the configuration file, possible values are:
- `'table'`: File changes walkthrough table will be displayed on the top of the "Files changed" tab, in addition to the "Conversation" tab.
- `true`: A collapsable file comment with changes title and a changes summary for each file in the PR.
- `false` (default): File changes walkthrough will be added only to the "Conversation" tab.
<tr><td><details> <summary><strong> Utilizing extra instructions</strong></summary><hr>

The `describe` tool can be configured with extra instructions, to guide the model to a feedback tailored to the needs of your project.

Be specific, clear, and concise in the instructions. With extra instructions, you are the prompter. Notice that the general structure of the description is fixed, and cannot be changed. Extra instructions can change the content or style of each sub-section of the PR description.

Examples for extra instructions:
```
[pr_description] 
extra_instructions="""
- The PR title should be in the format: '<PR type>: <title>'
- The title should be short and concise (up to 10 words)
- ...
"""
```
Use triple quotes to write multi-line instructions. Use bullet points to make the instructions more readable.

</details></td></tr>

<tr><td><details> <summary><strong> More PR-Agent commands</strong></summary><hr> 

> To invoke the PR-Agent, add a comment using one of the following commands:  
> - **/review**: Request a review of your Pull Request.   
> - **/describe**: Update the PR title and description based on the contents of the PR.   
> - **/improve [--extended]**: Suggest code improvements. Extended mode provides a higher quality feedback.   
> - **/ask \<QUESTION\>**: Ask a question about the PR.   
> - **/update_changelog**: Update the changelog based on the PR's contents.   
> - **/add_docs** 💎: Generate docstring for new components introduced in the PR.   
> - **/generate_labels** 💎: Generate labels for the PR based on the PR's contents.   
> - **/analyze** 💎: Automatically analyzes the PR, and presents changes walkthrough for each component.   

>See the [tools guide](https://github.com/Codium-ai/pr-agent/blob/main/docs/TOOLS_GUIDE.md) for more details.
>To list the possible configuration parameters, add a **/config** comment.   
 

</details></td></tr>

</table>

See the [describe usage](https://github.com/Codium-ai/pr-agent/blob/main/docs/DESCRIBE.md) page for a comprehensive guide on using this tool.

</details>

### CODE REVIEW

**Comment by mrT23** [comment]
i don't object to this, but it should be a parameter controlled from the configuration file

**Comment by Majdoddin** [comment]
Thank you for reviewing the PR. 
I understand your point, but the current implementation assumes that `frequency_penalty` (along with `temperature`) is set in the prompt toml:
https://github.com/Codium-ai/AlphaCodium/blob/ced8fee38b30bea2f8de00141b6976fd994565c5/alpha_codium/settings/code_contests_prompts_reflect.toml#L1-L3
https://github.com/Codium-ai/AlphaCodium/blob/ced8fee38b30bea2f8de00141b6976fd994565c5/alpha_codium/gen/coding_competitor.py#L47

Should `frequency_penalty` be read from `configuration.toml` instead? Meaning  the same value for all prompts?

**Comment by mrT23** [comment]
@Majdoddin 
i initially set `frequency_penalty` only to stages where I saw this infinite response problem.
if you saw it also in other stages, maybe its best to add it to all stages.

so yes, read this parameter from `configuration.toml` and add it to the different stages

**Comment by Majdoddin** [comment]
@mrT23 done.

**Review by mrT23 — APPROVED** [review]

**Pull request merged**
