### PR TITLE
#53   Fix ImportError: cannot import name 'model_validator' from 'pydantic'

### LINKED ISSUE #53: ImportError: cannot import name 'model_validator' from 'pydantic'
## Might be version conflict of pydantic and litellm
- I'm trying to solve my own example and get this error

```bash
python -m alpha_codium.solve_my_problem \   
--my_problem_json_file example.json            
Traceback (most recent call last):
  File "/Users/hieunguyenminh/opt/anaconda3/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/hieunguyenminh/opt/anaconda3/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/hieunguyenminh/CODE ALL/Research/AlphaCodium/alpha_codium/solve_my_problem.py", line 4, in <module>
    from alpha_codium.gen.coding_competitor import solve_problem, solve_my_problem
  File "/Users/hieunguyenminh/CODE ALL/Research/AlphaCodium/alpha_codium/gen/coding_competitor.py", line 17, in <module>
    from alpha_codium.llm.ai_handler import AiHandler
  File "/Users/hieunguyenminh/CODE ALL/Research/AlphaCodium/alpha_codium/llm/ai_handler.py", line 4, in <module>
    import litellm
  File "/Users/hieunguyenminh/CODE ALL/Research/AlphaCodium/venv/lib/python3.9/site-packages/litellm/__init__.py", line 17, in <module>
    from litellm.proxy._types import (
  File "/Users/hieunguyenminh/CODE ALL/Research/AlphaCodium/venv/lib/python3.9/site-packages/litellm/proxy/_types.py", line 1, in <module>
    from pydantic import BaseModel, Extra, Field, model_validator, Json, ConfigDict
ImportError: cannot import name 'model_validator' from 'pydantic' (/Users/hieunguyenminh/CODE ALL/Research/AlphaCodium/venv/lib/python3.9/site-packages/pydantic/__init__.cpython-39-darwin.so)
```

### PR DESCRIPTION
**Pull request by GovindHede**
### **User description**
**Fix ImportError:**   cannot import name 'model_validator' from 'pydantic'

### **Description**
This PR fixes the ImportError caused by attempting to import `model_validator` from an incompatible version of Pydantic. It ensures that the correct version of Pydantic is used and includes a fallback for compatibility.

###**Changes**
- Added conditional import for `model_validator`, `Json`, and `ConfigDict` from Pydantic with fallback in `_types.py`.
- Introduced multiple Pydantic models and enums for LiteLLM proxy configuration and request handling in `_types.py`.
- Implemented custom validators using `model_validator` in `_types.py`.
- Added `.gitattributes` file to normalize line endings and specified line ending rules for different file types.
- Updated Pydantic version to >= 2.8.2 in `requirements.txt`.

###** Testing**
- Verified that the import error is resolved.
- Ran existing tests to ensure no other functionality is affected.

### Issue Reference
Fixes #53

___

### **PR Type**
Bug fix, Enhancement

### CODE REVIEW

**Comment by mrT23** [comment]
Hi @GovindHede 
thanks for the PR.

isnt there a way to fix it without a 1700 lines new file ?

**Comment by GovindHede** [comment]
Hi @mrT23 ,

Thank you for reviewing my PR.

I understand your concern regarding the size of the changes. The issue with importing 'model_validator' from an incompatible version of Pydantic required a conditional import to ensure compatibility across different versions. To address this, I updated '_types.py ' to handle the import error gracefully.

However, I am open to suggestions for a more concise solution if you have any specific recommendations. Please let me know if there are any parts of the changes that you think can be streamlined or if there's an alternative approach you'd prefer.

Looking forward to your feedback!

Best regards,
Govind Hede

**Review by mrT23 — APPROVED** [review]

**Comment by mrT23** [comment]
@GovindHede 
ok, thanks for the fix.

let's merge it for now, and if I will come across something more concise for this pydantic issue, I will revisit it

**Comment by GovindHede** [comment]
Hi @mrT23 ,

Thank you for merging the fix! I appreciate your understanding. This is actually my first open-source contribution, so I'm thrilled to have had the opportunity. I'll keep an eye out for any further improvements we can make regarding the Pydantic issue.

**Pull request merged**
